// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MfaQrsColumns holds the columns for the "mfa_qrs" table.
	MfaQrsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "secret", Type: field.TypeBytes, Size: 256, SchemaType: map[string]string{"mysql": "varbinary"}},
		{Name: "user_id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "binary(16)"}},
	}
	// MfaQrsTable holds the schema information for the "mfa_qrs" table.
	MfaQrsTable = &schema.Table{
		Name:       "mfa_qrs",
		Columns:    MfaQrsColumns,
		PrimaryKey: []*schema.Column{MfaQrsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mfa_qrs_users_mfa_qrs",
				Columns:    []*schema.Column{MfaQrsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mfaqr_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{MfaQrsColumns[5], MfaQrsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						MfaQrsColumns[1].Name: true,
					},
				},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"mysql": "binary(16)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 256},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "login_method", Type: field.TypeEnum, Enums: []string{"password", "mfa-qr", "passkey"}, Default: "mfa-qr"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MfaQrsTable,
		UsersTable,
	}
)

func init() {
	MfaQrsTable.ForeignKeys[0].RefTable = UsersTable
}
