// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nidan-kai/ent/mfaqr"
	"nidan-kai/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MfaQr is the model entity for the MfaQr schema.
type MfaQr struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Secret holds the value of the "secret" field.
	Secret []byte `json:"secret,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MfaQrQuery when eager-loading is set.
	Edges        MfaQrEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MfaQrEdges holds the relations/edges for other nodes in the graph.
type MfaQrEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MfaQrEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MfaQr) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mfaqr.FieldSecret:
			values[i] = new([]byte)
		case mfaqr.FieldID, mfaqr.FieldUserID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MfaQr fields.
func (_m *MfaQr) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mfaqr.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case mfaqr.FieldSecret:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret", values[i])
			} else if value != nil {
				_m.Secret = *value
			}
		case mfaqr.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MfaQr.
// This includes values selected through modifiers, order, etc.
func (_m *MfaQr) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the MfaQr entity.
func (_m *MfaQr) QueryUser() *UserQuery {
	return NewMfaQrClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this MfaQr.
// Note that you need to call MfaQr.Unwrap() before calling this method if this MfaQr
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MfaQr) Update() *MfaQrUpdateOne {
	return NewMfaQrClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MfaQr entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MfaQr) Unwrap() *MfaQr {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MfaQr is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MfaQr) String() string {
	var builder strings.Builder
	builder.WriteString("MfaQr(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("secret=")
	builder.WriteString(fmt.Sprintf("%v", _m.Secret))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteByte(')')
	return builder.String()
}

// MfaQrs is a parsable slice of MfaQr.
type MfaQrs []*MfaQr
