// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nidan-kai/ent/mfaqr"
	"nidan-kai/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MfaQrDelete is the builder for deleting a MfaQr entity.
type MfaQrDelete struct {
	config
	hooks    []Hook
	mutation *MfaQrMutation
}

// Where appends a list predicates to the MfaQrDelete builder.
func (_d *MfaQrDelete) Where(ps ...predicate.MfaQr) *MfaQrDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MfaQrDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MfaQrDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MfaQrDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mfaqr.Table, sqlgraph.NewFieldSpec(mfaqr.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MfaQrDeleteOne is the builder for deleting a single MfaQr entity.
type MfaQrDeleteOne struct {
	_d *MfaQrDelete
}

// Where appends a list predicates to the MfaQrDelete builder.
func (_d *MfaQrDeleteOne) Where(ps ...predicate.MfaQr) *MfaQrDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MfaQrDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mfaqr.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MfaQrDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
