// Code generated by ent, DO NOT EDIT.

package ent

import (
	"nidan-kai/ent/mfaqr"
	"nidan-kai/ent/schema"
	"nidan-kai/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mfaqrMixin := schema.MfaQr{}.Mixin()
	mfaqrMixinFields0 := mfaqrMixin[0].Fields()
	_ = mfaqrMixinFields0
	mfaqrFields := schema.MfaQr{}.Fields()
	_ = mfaqrFields
	// mfaqrDescCreatedAt is the schema descriptor for created_at field.
	mfaqrDescCreatedAt := mfaqrMixinFields0[0].Descriptor()
	// mfaqr.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfaqr.DefaultCreatedAt = mfaqrDescCreatedAt.Default.(func() time.Time)
	// mfaqrDescUpdatedAt is the schema descriptor for updated_at field.
	mfaqrDescUpdatedAt := mfaqrMixinFields0[1].Descriptor()
	// mfaqr.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mfaqr.DefaultUpdatedAt = mfaqrDescUpdatedAt.Default.(func() time.Time)
	// mfaqr.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mfaqr.UpdateDefaultUpdatedAt = mfaqrDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mfaqrDescSecret is the schema descriptor for secret field.
	mfaqrDescSecret := mfaqrFields[1].Descriptor()
	// mfaqr.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	mfaqr.SecretValidator = func() func([]byte) error {
		validators := mfaqrDescSecret.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
			validators[2].(func([]byte) error),
		}
		return func(secret []byte) error {
			for _, fn := range fns {
				if err := fn(secret); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
