// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldLoginMethod holds the string denoting the login_method field in the database.
	FieldLoginMethod = "login_method"
	// EdgeMfaQrs holds the string denoting the mfa_qrs edge name in mutations.
	EdgeMfaQrs = "mfa_qrs"
	// Table holds the table name of the user in the database.
	Table = "users"
	// MfaQrsTable is the table that holds the mfa_qrs relation/edge.
	MfaQrsTable = "mfa_qrs"
	// MfaQrsInverseTable is the table name for the MfaQr entity.
	// It exists in this package in order to avoid circular dependency with the "mfaqr" package.
	MfaQrsInverseTable = "mfa_qrs"
	// MfaQrsColumn is the table column denoting the mfa_qrs relation/edge.
	MfaQrsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldEmail,
	FieldLoginMethod,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
)

// LoginMethod defines the type for the "login_method" enum field.
type LoginMethod string

// LoginMethodPassword is the default value of the LoginMethod enum.
const DefaultLoginMethod = LoginMethodPassword

// LoginMethod values.
const (
	LoginMethodPassword LoginMethod = "password"
	LoginMethodMfaQr    LoginMethod = "mfa-qr"
	LoginMethodPasskey  LoginMethod = "passkey"
)

func (lm LoginMethod) String() string {
	return string(lm)
}

// LoginMethodValidator is a validator for the "login_method" field enum values. It is called by the builders before save.
func LoginMethodValidator(lm LoginMethod) error {
	switch lm {
	case LoginMethodPassword, LoginMethodMfaQr, LoginMethodPasskey:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for login_method field: %q", lm)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByLoginMethod orders the results by the login_method field.
func ByLoginMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginMethod, opts...).ToFunc()
}

// ByMfaQrsCount orders the results by mfa_qrs count.
func ByMfaQrsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMfaQrsStep(), opts...)
	}
}

// ByMfaQrs orders the results by mfa_qrs terms.
func ByMfaQrs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMfaQrsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMfaQrsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MfaQrsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MfaQrsTable, MfaQrsColumn),
	)
}
